<?php
include("Soap_header_token_DataSchedule.php");
include('call_core_orgid.php');
try {
$param_Schedule=array("ScheduleID"=>11406);
$response_Schedule =$DataScheduleWS ->__soapCall('GetDataSchedule',array($param_Schedule));

echo '<pre>';
//print_r($response_Schedule);

$result_Schedule=$response_Schedule->GetDataScheduleResult;

$result_Schedule_ID=$result_Schedule->ID;
$result_Schedule_Description=$result_Schedule->Description;
$result_Schedule_ScheduleObjectType=$result_Schedule->ScheduleObjectType;
$result_Schedule_SubjectID=$result_Schedule->SubjectID;
$result_Schedule_IsFullDownload=$result_Schedule->IsFullDownload;
$result_Schedule_ScheduleType=$result_Schedule->ScheduleType;
$result_Schedule_StartTime=$result_Schedule->StartTime;
$result_Schedule_DaysActive=$result_Schedule->DaysActive;
$result_Schedule_NextRunTime=$result_Schedule->NextRunTime;
$result_Schedule_MaxRetries=$result_Schedule->MaxRetries;
$result_Schedule_RetryDelayMinutes=$result_Schedule->RetryDelayMinutes;
$result_Schedule_DownloadStatus=$result_Schedule->DownloadStatus;
$result_Schedule_SynchroniseClock=$result_Schedule->SynchroniseClock;
$result_Schedule_DisarmUnit=$result_Schedule->DisarmUnit;
$result_Schedule_DriverIDToSet=$result_Schedule->DriverIDToSet;
$result_Schedule_SetOdometer=$result_Schedule->SetOdometer;
$result_Schedule_SetOdometerTo=$result_Schedule->SetOdometerTo;
$result_Schedule_SetEngineHours=$result_Schedule->SetEngineHours;
$result_Schedule_SetEngineHoursInSecondsTo=$result_Schedule->SetEngineHoursInSecondsTo;
$result_Schedule_PerformDataTransfer=$result_Schedule->PerformDataTransfer;
$result_Schedule_IntervalDataDownloadType=$result_Schedule->IntervalDataDownloadType;
$result_Schedule_IntervalDataStartTime=$result_Schedule->IntervalDataStartTime;
$date_start = new DateTime($result_Schedule_IntervalDataStartTime);
$result_Schedule_IntervalDataEndTime=$result_Schedule->IntervalDataEndTime;
$date_end = new DateTime($result_Schedule_IntervalDataEndTime);
$result_Schedule_UploadConfiguration=$result_Schedule->UploadConfiguration;
$result_Schedule_UploadDeviceDrivers=$result_Schedule->UploadDeviceDrivers;
$result_Schedule_TimeoutMinutes=$result_Schedule->TimeoutMinutes;
$result_Schedule_CallMeBackIfNoCoverage=$result_Schedule->CallMeBackIfNoCoverage;
$result_Schedule_CallMeBackForConfigUpload=$result_Schedule->CallMeBackForConfigUpload;
$result_Schedule_TransportID=$result_Schedule->TransportID;
$result_Schedule_IsCustomerInitiated=$result_Schedule->IsCustomerInitiated;
$result_Schedule_SystemScheduleType=$result_Schedule->SystemScheduleType;
$result_Schedule_Priority=$result_Schedule->Priority;
$result_Schedule_UploadTerminalScript=$result_Schedule->UploadTerminalScript;
$result_Schedule_UploadTerminalScriptForced=$result_Schedule->UploadTerminalScriptForced;
$result_Schedule_UploadTerminalDdm=$result_Schedule->UploadTerminalDdm;
$result_Schedule_UploadTerminalDdmForced=$result_Schedule->UploadTerminalDdmForced;
$result_Schedule_UploadTerminalDb=$result_Schedule->UploadTerminalDb;
$result_Schedule_UploadTerminalDbForced=$result_Schedule->UploadTerminalDbForced;
$result_Schedule_UploadCanDdm=$result_Schedule->UploadCanDdm;
$result_Schedule_UploadCanDdmForced=$result_Schedule->UploadCanDdmForced;
$result_Schedule_UploadExtendedConfig=$result_Schedule->UploadExtendedConfig;
$result_Schedule_UploadExtendedConfigForced=$result_Schedule->UploadExtendedConfigForced;
$result_Schedule_UploadExtendedConfigInTrip=$result_Schedule->UploadExtendedConfigInTrip;
$result_Schedule_IgnoreArmedCheckForDdxUpload=$result_Schedule->IgnoreArmedCheckForDdxUpload;
$result_Schedule_MessageToLog=$result_Schedule->MessageToLog;
} catch (SoapFault $fault) {
    trigger_error("SOAP Fault: (faultcode: {$fault->faultcode}, faultstring: {$fault->faultstring})", E_USER_ERROR);
}
print_r("ID.".$result_Schedule_ID);
print "\t";
print_r("Description.".$result_Schedule_Description);
print "\t";
print_r("ScheduleObjectType.".$result_Schedule_ScheduleObjectType);
print "\t";
print_r("SubjectID.".$result_Schedule_SubjectID);
print "\t";
print_r("IsFullDownload.".$result_Schedule_IsFullDownload);
print "\t";
print_r("ScheduleType.".$result_Schedule_ScheduleType);
print "\t";
print_r("StartTime.".$result_Schedule_StartTime);
print "\t";
print_r("DaysActive.".$result_Schedule_DaysActive);
print "\t";
print_r("NextRunTime.".$result_Schedule_NextRunTime);
print "\t";
print_r("MaxRetries.".$result_Schedule_MaxRetries);
print "\t";
print_r("MaxRetries.".$result_Schedule_RetryDelayMinutes);
print "\t";
print_r("DownloadStatus.".$result_Schedule_DownloadStatus);
print "\t";
print_r("SynchroniseClock.".$result_Schedule_SynchroniseClock);
print "\t";
print_r("DisarmUnit.".$result_Schedule_DisarmUnit);
print "\t";
print_r("DriverIDToSet.".$result_Schedule_DriverIDToSet);
print "\t";
print_r("SetOdometer.".$result_Schedule_SetOdometer);
print "\t";
print_r("SetOdometerTo.".$result_Schedule_SetOdometerTo);
print "\t";
print_r("SetEngineHours.".$result_Schedule_SetEngineHours);
print "\t";
print_r("SetEngineHoursInSecondsTo.".$result_Schedule_SetEngineHoursInSecondsTo);
print "\t";
print_r("PerformDataTransfer.".$result_Schedule_PerformDataTransfer);
print "\t";
print_r("IntervalDataDownloadType.".$result_Schedule_IntervalDataDownloadType);
print "\t";
print "IntervalDataStartTime.".$date_start->format('d/m/Y (H:i:s)');
print "\t";
print "IntervalDataEndTime.".$date_end->format('d/m/Y (H:i:s)');
print "\t";
print_r("UploadConfiguration.".$result_Schedule_UploadConfiguration);
print "\t";
print_r("UploadDeviceDrivers.".$result_Schedule_UploadDeviceDrivers);
print "\t";
print_r("TimeoutMinutes.".$result_Schedule_TimeoutMinutes);
print "\t";
print_r("CallMeBackIfNoCoverage.".$result_Schedule_CallMeBackIfNoCoverage);
print "\t";
print_r("CallMeBackForConfigUpload.".$result_Schedule_CallMeBackIfNoCoverage);
print "\t";
print_r("TransportID.".$result_Schedule_TransportID);
print "\t";
print_r("IsCustomerInitiated.".$result_Schedule_IsCustomerInitiated);
print "\t";
print_r("SystemScheduleType.".$result_Schedule_SystemScheduleType);
print "\t";
print_r("Priority.".$result_Schedule_Priority);
print "\t";
print_r("UploadTerminalScript.".$result_Schedule_UploadTerminalScript);
print "\t";
print_r("UploadTerminalScriptForced.".$result_Schedule_UploadTerminalScriptForced);
print "\t";
print_r("UploadTerminalDdm.".$result_Schedule_UploadTerminalDdm);
print "\t";
print_r("UploadTerminalDdmForced.".$result_Schedule_UploadTerminalDdmForced);
print "\t";
print_r("UploadTerminalDb.".$result_Schedule_UploadTerminalDb);
print "\t";
print_r("UploadTerminalDbForced.".$result_Schedule_UploadTerminalDbForced);
print "\t";
print_r("UploadCanDdm.".$result_Schedule_UploadCanDdm);
print "\t";
print_r("UploadCanDdmForced.".$result_Schedule_UploadCanDdmForced);
print "\t";
print_r("UploadExtendedConfig.".$result_Schedule_UploadExtendedConfig);
print "\t";
print_r("UploadExtendedConfigForced.".$result_Schedule_UploadExtendedConfigForced);
print "\t";
print_r("UploadExtendedConfigInTrip.".$result_Schedule_UploadExtendedConfigInTrip);
print "\t";
print_r("IgnoreArmedCheckForDdxUpload.".$result_Schedule_IgnoreArmedCheckForDdxUpload);
print "\t";
print_r("MessageToLog.".$result_Schedule_MessageToLog);
print "\t";
?>