<?php
include("Soap_header_token_TripProcesses.php");
include('call_core_orgid.php');
try {
$StartDateTime='2016-01-14T00:00:00';
$EndDateTime='2016-01-14T23:59:59';
$param_Trip_totals_vehicle_daterange=array("vehicleId"=>917,"StartDateTime"=>$StartDateTime ,"EndDateTime"=>$EndDateTime);
$response_Trip_totals_vehicle_daterange =$TripsProcessesWS ->__soapCall('GetTripsWithTotalsForVehicleInDateRange',array($param_Trip_totals_vehicle_daterange));

echo '<pre>';
//print_r($response_Trip_totals_driver_daterange);

$result_Trip_total_daterange=$response_Trip_totals_vehicle_daterange->GetTripsWithTotalsForVehicleInDateRangeResult->TripWithTotals;
for($i=0;$i<count($result_Trip_total_daterange);$i++){
$result_Trip_total_daterange_id=$result_Trip_total_daterange[$i]->ID;
$result_Trip_total_daterange_Trip_VehicleID=$result_Trip_total_daterange[$i]->Trip->VehicleID;
$result_Trip_total_daterange_Trip_TripNo=$result_Trip_total_daterange[$i]->Trip->TripNo;
$result_Trip_total_daterange_Trip_DriverID=$result_Trip_total_daterange[$i]->Trip->DriverID;
$result_Trip_total_daterange_Trip_OriginalDriverID=$result_Trip_total_daterange[$i]->Trip->OriginalDriverID;
$result_Trip_total_daterange_Trip_TripStart=$result_Trip_total_daterange[$i]->Trip->TripStart;
$date_Trip_start = new DateTime($result_Trip_total_daterange_Trip_TripStart);
$result_Trip_total_daterange_Trip_TripEnd=$result_Trip_total_daterange[$i]->Trip->TripEnd;
$date_Trip_end = new DateTime($result_Trip_total_daterange_Trip_TripEnd);
$result_Trip_total_daterange_Trip_CategoryID=$result_Trip_total_daterange[$i]->Trip->CategoryID;
$result_Trip_total_daterange_StartSubTripSeq=$result_Trip_total_daterange[$i]->StartSubTripSeq;
$result_Trip_total_daterange_EndSubTripSeq=$result_Trip_total_daterange[$i]->EndSubTripSeq;
$result_Trip_total_daterange_TripDistance=$result_Trip_total_daterange[$i]->TripDistance;
$result_Trip_total_daterange_Odometer=$result_Trip_total_daterange[$i]->Odometer;
$result_Trip_total_daterange_MaxSpeed=$result_Trip_total_daterange[$i]->MaxSpeed;
$result_Trip_total_daterange_SpeedTime=$result_Trip_total_daterange[$i]->SpeedTime;
$result_Trip_total_daterange_SpeedOccurs=$result_Trip_total_daterange[$i]->SpeedOccurs;
$result_Trip_total_daterange_MaxBrake=$result_Trip_total_daterange[$i]->MaxBrake;
$result_Trip_total_daterange_BrakeTime=$result_Trip_total_daterange[$i]->BrakeTime;
$result_Trip_total_daterange_BrakeOccurs=$result_Trip_total_daterange[$i]->BrakeOccurs;
$result_Trip_total_daterange_MaxAccel=$result_Trip_total_daterange[$i]->MaxAccel;
$result_Trip_total_daterange_AccelTime=$result_Trip_total_daterange[$i]->AccelTime;
$result_Trip_total_daterange_AccelOccurs=$result_Trip_total_daterange[$i]->AccelOccurs;
$result_Trip_total_daterange_MaxRPM=$result_Trip_total_daterange[$i]->MaxRPM;
$result_Trip_total_daterange_RPMTime=$result_Trip_total_daterange[$i]->RPMTime;
$result_Trip_total_daterange_RPMOccurs=$result_Trip_total_daterange[$i]->RPMOccurs;
$result_Trip_total_daterange_GBTime=$result_Trip_total_daterange[$i]->GBTime;
$result_Trip_total_daterange_ExIdleTime=$result_Trip_total_daterange[$i]->ExIdleTime;
$result_Trip_total_daterange_ExIdleOccurs=$result_Trip_total_daterange[$i]->ExIdleTime;
$result_Trip_total_daterange_NIdleTime=$result_Trip_total_daterange[$i]->NIdleTime;
$result_Trip_total_daterange_NIdleOccurs=$result_Trip_total_daterange[$i]->NIdleOccurs;
$result_Trip_total_daterange_StandingTime=$result_Trip_total_daterange[$i]->StandingTime;
$result_Trip_total_daterange_Litres=$result_Trip_total_daterange[$i]->Litres;
$result_Trip_total_daterange_StartGPSID=$result_Trip_total_daterange[$i]->StartGPSID;
$result_Trip_total_daterange_EndGPSID=$result_Trip_total_daterange[$i]->EndGPSID;
$result_Trip_total_daterange_StartEngineSeconds=$result_Trip_total_daterange[$i]->StartEngineSeconds;
$result_Trip_total_daterange_EndEngineSeconds=$result_Trip_total_daterange[$i]->EndEngineSeconds;
} catch (SoapFault $fault) {
    trigger_error("SOAP Fault: (faultcode: {$fault->faultcode}, faultstring: {$fault->faultstring})", E_USER_ERROR);
}
print_r("ID.".$result_Trip_total_daterange_id);
print "\t";
print_r("VehicleID.".$result_Trip_total_daterange_Trip_VehicleID);
print "\t";
print_r("TripNo.".$result_Trip_total_daterange_Trip_TripNo);
print "\t";
print_r("DriverID.".$result_Trip_total_daterange_Trip_DriverID);
print "\t";
print_r("OriginalDriverID.".$result_Trip_total_daterange_Trip_OriginalDriverID);
print "\t";
print "TripStart.".$date_Trip_start->format('d/m/Y (H:i:s)');
print "\t";
print "TripEnd.".$date_Trip_end->format('d/m/Y (H:i:s)');
print "\t";
print_r("StartSubTripSeq.".$result_Trip_total_daterange_StartSubTripSeq);
print "\t";
print_r("EndSubTripSeq.".$result_Trip_total_daterange_EndSubTripSeq);
print "\t";
print_r("TripDistance.".$result_Trip_total_daterange_TripDistance);
print "\t";
print_r("Odometer.".$result_Trip_total_daterange_Odometer);
print "\t";
print_r("MaxSpeed.".$result_Trip_total_daterange_MaxSpeed);
print "\t";
print_r("SpeedTime.".$result_Trip_total_daterange_SpeedTime);
print "\t";
print_r("SpeedOccurs.".$result_Trip_total_daterange_SpeedTime);
print "\t";
print_r("MaxBrake.".$result_Trip_total_daterange_MaxBrake);
print "\t";
print_r("BrakeTime.".$result_Trip_total_daterange_BrakeTime);
print "\t";
print_r("BrakeOccurs.".$result_Trip_total_daterange_BrakeOccurs);
print "\t";
print_r("MaxAccel.".$result_Trip_total_daterange_MaxAccel);
print "\t";
print_r("AccelTime.".$result_Trip_total_daterange_AccelTime);
print "\t";
print_r("AccelOccurs.".$result_Trip_total_daterange_AccelOccurs);
print "\t";
print_r("MaxRPM.".$result_Trip_total_daterange_MaxRPM);
print "\t";
print_r("RPMTime.".$result_Trip_total_daterange_RPMTime);
print "\t";
print_r("RPMOccurs.".$result_Trip_total_daterange_RPMOccurs);
print "\t";
print_r("RPMOccurs.".$result_Trip_total_daterange_RPMOccurs);
print "\t";
print_r("GBTime.".$result_Trip_total_daterange_GBTime);
print "\t";
print_r("ExIdleTime.".$result_Trip_total_daterange_ExIdleTime);
print "\t";
print_r("ExIdleOccurs.".$result_Trip_total_daterange_ExIdleOccurs);
print "\t";
print_r("NIdleTime.".$result_Trip_total_daterange_NIdleTime);
print "\t";
print_r("NIdleOccurs.".$result_Trip_total_daterange_NIdleOccurs);
print "\t";
print_r("StandingTime.".$result_Trip_total_daterange_StandingTime);
print "\t";
print_r("Litres.".$result_Trip_total_daterange_Litres);
print "\t";
print_r("StartGPSID.".$result_Trip_total_daterange_StartGPSID);
print "\t";
print_r("EndGPSID.".$result_Trip_total_daterange_EndGPSID);
print "\t";
print_r("StartEngineSeconds.".$result_Trip_total_daterange_StartEngineSeconds);
print "\t";
print_r("EndEngineSeconds.".$result_Trip_total_daterange_EndEngineSeconds);
print "\t";

echo '<br>';
}
?>